name: Publish NPM Packages with Lerna

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0

      - name: Install Dependencies
        run: npm install

      - name: Build Lerna
        run: npx lerna run build

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{  secrets.NPM_AUTH_TOKEN  }}" > ~/.npmrc

      - name: Set up Git Authentication
        run: |
          git config --global credential.helper store
          git config --global credential.helper 'cache --timeout=3600'
          git config --global user.name "AnnaSydorova"
          git config --global user.email "mariafadeeva4155@gmail.com"
          git remote set-url origin "https://AnnaSydorova:${{ secrets.GH_TOKEN }}@github.com/AnnaSydorova/demo-library.git"

      - name: Publish NPM Packages
        run: npx lerna publish minor --yes
